package twitter;

import java.util.ArrayList;
import java.util.Iterator;
import twitter4j.Query;
import twitter4j.QueryResult;
import twitter4j.Status;
import twitter4j.Twitter;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;
import twitter4j.conf.ConfigurationBuilder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mos_s
 */
public class Twitter4J extends javax.swing.JFrame {

    /**
     * Creates new form Twitter4J
     */
    public Twitter4J() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        userResult1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        userButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userResult = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        word = new javax.swing.JTextField();
        wordButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        wordResult = new javax.swing.JTextArea();

        jScrollPane2.setAutoscrolls(true);

        userResult1.setColumns(20);
        userResult1.setLineWrap(true);
        userResult1.setRows(5);
        jScrollPane2.setViewportView(userResult1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Twitter4J");

        jLabel2.setText("Search user :");

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        userButton.setText("search");
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);

        userResult.setColumns(20);
        userResult.setLineWrap(true);
        userResult.setRows(5);
        jScrollPane1.setViewportView(userResult);

        jLabel3.setText("Search word :");

        wordButton.setText("search");
        wordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordButtonActionPerformed(evt);
                mos(evt);
            }
        });

        jScrollPane3.setAutoscrolls(true);

        wordResult.setColumns(20);
        wordResult.setLineWrap(true);
        wordResult.setRows(5);
        jScrollPane3.setViewportView(wordResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userButton))
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(word, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(wordButton)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userButton)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(word, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(wordButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordButtonActionPerformed
        ConfigurationBuilder cf = new ConfigurationBuilder();

        //Config Setting
        

        Twitter twitter = new TwitterFactory(cf.build()).getInstance();
        
        ArrayList<Tweet> mos = new ArrayList<>();
        int size = 100;
        int count = 1;
        String str = "";
        String wd = "";
        try {
            wd = word.getText();
            Query query = new Query(word.getText());
            QueryResult result = twitter.search(query);
            while (mos.size() < size && result.hasNext()) {
                //query.setCount(100);
                result = twitter.search(result.nextQuery());
                for (Status status : result.getTweets()) {
                    
                    //System.out.println("number : " + count + " " + status.getUser().getScreenName() + ":" + status.getText());
                    //mos.add(count + " " + status.getUser().getScreenName() + ":" + status.getText());
                    mos.add(new Tweet(status.getUser().getScreenName(),status.getText()));
                    count++;
                    str += count + ") " + status.getUser().getScreenName() + ":" + status.getText()+ "\n";
                    
                }
            }
        } catch (TwitterException e) {
            //e.printStackTrace();
        }
        if(count >= 100){
            str += "There are " + count + " tweets about " + word.getText() + ".\n";
        }
        wordResult.setText(str);

        /*Iterator<Tweet> it = mos.iterator();
        while (it.hasNext()) {
            Tweet temp = it.next();
            str += temp.getUser() + " : " + temp.getTweet();
        }
        wordResult.setText("");*/
    }//GEN-LAST:event_wordButtonActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed

    }//GEN-LAST:event_userActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        ConfigurationBuilder cf = new ConfigurationBuilder();

        //Config Setting
        

        Twitter twitter = new TwitterFactory(cf.build()).getInstance();
        
        ArrayList<Tweet> mos = new ArrayList<>();
        int size = 100;
        int count = 1;
        String str = "";
        String wd = "";
        try {
            wd = word.getText();
            Query query = new Query(word.getText());
            QueryResult result = twitter.search(query);
            while (mos.size() < size && result.hasNext()) {
                //query.setCount(100);
                result = twitter.search(result.nextQuery());
                for (Status status : result.getTweets()) {
                    
                    //System.out.println("number : " + count + " " + status.getUser().getScreenName() + ":" + status.getText());
                    //mos.add(count + " " + status.getUser().getScreenName() + ":" + status.getText());
                    mos.add(new Tweet(status.getUser().getScreenName(),status.getText()));
                    count++;
                    str += count + ") " + status.getUser().getScreenName() + "\n";
                    
                }
            }
        } catch (TwitterException e) {
            //e.printStackTrace();
        }
        if(count >= 100){
            str += "There are " + count + " users about " + word.getText() + ".\n";
        }
        userResult.setText(str);
  
    }//GEN-LAST:event_userButtonActionPerformed

    private void mos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mos
        // TODO add your handling code here:
    }//GEN-LAST:event_mos

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Twitter4J.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Twitter4J.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Twitter4J.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Twitter4J.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Twitter4J().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField user;
    private javax.swing.JButton userButton;
    private javax.swing.JTextArea userResult;
    private javax.swing.JTextArea userResult1;
    private javax.swing.JTextField word;
    private javax.swing.JButton wordButton;
    private javax.swing.JTextArea wordResult;
    // End of variables declaration//GEN-END:variables
}
